base:
  proxy: ""
media:
  library: vsmeta
  url: ""
  api: ""
  secretid: ""
  secretkey: ""
path:
  success: success
  fail: fail
  directory: '{number}'
  filter: -hd||hd-||_hd||hd_||[||]||【||】||asfur||~||-full||_full||3xplanet||monv||云中飘荡||@||tyhg999.com||xxxxxxxx||-fhd||_fhd||thz.la
  move: false
  repeat: true
  thread: 2
site:
  javbus: https://www.javbus.com/
  javdb: https://javdb.com/
